---
- include_tasks: grid_configure.yml
  vars:
   _type_install: "CRS_CONFIG"
  tags:  configure_grid
- name: Clean stage directory {{stage_dir}}  
  file:
    path: "{{stage_dir}}"
    state: absent
  with_items:
    - "{{ nodes }}"
  loop_control:
    loop_var: _oracle_nodes
    label: '[clean stage dir on  {{_oracle_nodes.name}}]'
  delegate_to: "{{ _oracle_nodes.ip_addr }}"
  become: true
  tags: clean_stage  




 